### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roirotoras012** [TheBoringDude/covid19ph-api#2]
Access to XMLHttpRequest at 'http://covid19-api-philippines.herokuapp.com/api/filter/region_res/Region%20X:%20Northern%20Mindanao' from origin 'http://localhost:8100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by tbdsux** [comment]
Acess to website is currently working.
